feat(component): Added Course Audit
UTDNebula/planner pull request #51
Opened 2021-07-07 21:33 UTC by wbne

Provides a table allowing users to manually add courses they've taken. 
Not implemented yet in any pages.

2021-07-07 22:34 UTC, WillieCubed commented
Before I review the PR, you should take a look at this build error.

Because the build logs aren't generally available, I'll just dump the logs for the failing build here:

```
> 14:30:01.164  	Cloning github.com/acmutd/nebula-web (Branch: feature/course-audit, Commit: e9c9e8b)
> 14:30:02.531  	Cloning completed: 1.367s
> 14:30:02.561  	Analyzing source code...
> 14:30:03.872  	Installing build runtime...
> 14:30:06.310  	Build runtime installed: 2.443s
> 14:30:09.079  	Looking up build cache...
> 14:30:09.494  	Build cache found. Downloading...
> 14:30:13.833  	Build cache downloaded [69.59 MB]: 4338.702ms
> 14:30:14.919  	Installing dependencies...
> 14:30:16.646  	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
> 14:30:18.731  	> nebula-web@0.1.0 postinstall /vercel/path0
> 14:30:18.731  	> husky install
> 14:30:18.802  	husky - Git hooks installed
> 14:30:19.204  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
> 14:30:19.204  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 14:30:19.204  	up to date in 3.842s
> 14:30:19.433  	124 packages are looking for funding
> 14:30:19.433  	  run `npm fund` for details
> 14:30:19.451  	Detected Next.js version: 11.0.1
> 14:30:19.452  	Running "npm run build"
> 14:30:19.659  	> nebula-web@0.1.0 build /vercel/path0
> 14:30:19.659  	> next build
> 14:30:20.390  	info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
> 14:30:20.541  	info  - Checking validity of types...
> 14:30:28.716  	Failed to compile.
> 14:30:28.717  	./components/planner/history/StudentHistoryView/CourseAudit.tsx:28:52
> 14:30:28.717  	Type error: An import path cannot end with a '.ts' extension. Consider importing '../../../../modules/common/data.js' instead.
> 14:30:28.717  	  26 | import InputLabel from '@material-ui/core/InputLabel';
> 14:30:28.717  	  27 | import FormControl from '@material-ui/core/FormControl';
> 14:30:28.717  	> 28 | import { Course, SemesterCode, GPA_MAPPINGS } from '../../../../modules/common/data.ts';
> 14:30:28.717  	     |                                                    ^
> 14:30:28.717  	  29 | 
> 14:30:28.717  	  30 | let selectedState = [];
> 14:30:28.718  	  31 | let tempData = [];
> 14:30:28.736  	npm ERR! code ELIFECYCLE
> 14:30:28.736  	npm ERR! errno 1
> 14:30:28.739  	npm ERR! nebula-web@0.1.0 build: `next build`
> 14:30:28.739  	npm ERR! Exit status 1
> 14:30:28.739  	npm ERR! 
> 14:30:28.739  	npm ERR! Failed at the nebula-web@0.1.0 build script.
> 14:30:28.739  	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 14:30:28.745  	npm ERR! A complete log of this run can be found in:
> 14:30:28.745  	npm ERR!     /vercel/.npm/_logs/2021-07-07T21_30_28_740Z-debug.log
> 14:30:28.757  	Error: Command "npm run build" exited with 1
> 
```

2021-07-08 17:48 UTC, WillieCubed commented
Just an FYI: it's not Vercel that's the issue. When importing [modules](https://www.typescriptlang.org/docs/handbook/modules.html) in TypeScript, you don't use file extensions.

2021-07-25 18:45 UTC, WillieCubed requested changes
Overall, great work! Before we merge this into the `develop`, you'll have to make a few changes and document all components/interfaces that you've made and resolve the other comments made on this PR.

2021-07-25 18:45 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +function EnhancedTableHead(props: EnhancedTableProps) {
What does this do?

2021-07-25 18:45 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const { classes, onSelectAllClick, order, orderBy, numSelected, rowCount, onRequestSort } = props;
```suggestion
function EnhancedTableHead({
  classes,
  onSelectAllClick,
  order,
  orderBy,
  numSelected,
  rowCount,
  onRequestSort
}: EnhancedTableProps) {
```
You can combine these two lines by destructuring the function parameters in the function header. See [this article](https://medium.com/@rileyhilliard/es6-destructuring-in-typescript-4c048a8e9e15) for more info.

2021-07-25 18:45 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/StudentHistoryView.tsx
> +import CourseAudit from './CourseAudit';
What is the purpose of these changes to this file?

2021-07-25 18:45 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +          rowsPerPageOptions={[5, 10, 25]}
Extract the value of this item to a `const` variable outside the function. Right now, this appears like a list of [magic numbers](https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad#:~:text=In%20programming%2C%20a%20%22magic%20number,in%20more%20than%20one%20place.).

2021-07-25 18:45 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const handleChangePage = (event: unknown, newPage: number) => {
Don't use `unknown` for function parameters unless you know for a fact the value is unknown. For type completion, it's better to have well-defined types.

2021-07-25 18:45 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const [rows, setRows] = React.useState<CourseTaken[]>(tempData);
Do you think combining these into one or a few `React.useState` calls would make more sense here?

2021-07-25 18:45 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +let denseState;
Don't use top-level variables to store component state. Component state should be stored within each component.

2021-07-27 23:35 UTC, WillieCubed commented
Additionally, the component needs to be displayed in the user's profile in a "Attempted House History" section before this is merged into `develop.`

2021-07-30 20:56 UTC, WillieCubed commented
#### 📝Changed routes:


| [**/app/profile**](https://nebula-web-do3hsic03-acmutd.vercel.app/app/profile) |
|:-:|
|<a href="https://nebula-web-do3hsic03-acmutd.vercel.app/app/profile"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/W9ADX_V6fhfnH8CoDHWDcV-fElJpBKuKcc7pE7J_hafjyKfsp4ysgQOANy0GKSyllPylsJBnpyDfy8a_zcGgCg.png&w=600" alt="Screenshot of /app/profile" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xQ9dxXecv_6GtAl1OpyX_fdAhGCv3ee0SLbB6gvR_aYAWXxV42m4NhiExxlz27ohql7wgTrpfj_ttVDff7x5xg.png">(view full size)</a> |







Commit e5354b48691f1b190b9395a4b19db6ab78f1476a (https://nebula-web-do3hsic03-acmutd.vercel.app).

2021-07-30 21:05 UTC, wbne commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const [rows, setRows] = React.useState<CourseTaken[]>(tempData);
I'm not sure how to do it since most are independent of each other. However I have been able to delete some of the states making it slightly smaller.

2021-07-30 21:07 UTC, wbne commented on components/planner/history/StudentHistoryView/StudentHistoryView.tsx
> +import CourseAudit from './CourseAudit';
I wasn't sure how CourseAudit.tsx would be implemented so I had put it there just in case. It has now been removed.

2021-07-30 21:08 UTC, wbne commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +const headCells: HeadCell[] = [
List of column headers.

2021-07-30 21:09 UTC, wbne commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  if (orderBy === 'semester') {
Each column has a different way to determine which one is larger than the other. (eg. grade uses GPA while names simply using the default comparator operation)

2021-07-30 21:10 UTC, wbne commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const { classes, onSelectAllClick, order, orderBy, numSelected, rowCount, onRequestSort } = props;
Added to the code

2021-07-30 21:11 UTC, wbne commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +function EnhancedTableHead(props: EnhancedTableProps) {
Renders the column headers and shows whether the sorted category is ascending or descending.

2021-07-31 20:27 UTC, wbne commented
For the reroute, do I need to do anything else? I think I have completed the suggested changes.

2021-08-01 19:22 UTC, WillieCubed requested changes
# Feedback on Commits
Try to make your commit messages more user-facing and high-level like "Add ability to view previously attempted courses". It'll take some practice, but making your commit messages read like that will make it clear to new contributors what changed.

Also, for our purposes, you don't need to specify the filenames in the scope `feat(profile.tsx)` because it's clear from the commits what files were changed. Additionally, you didn't need to specify the scope for `fix((courseaudit.tsx)): Fix visual bugs and typing` (It could have just been `fix: Fix visual bugs and typing`).

For future reference: the current scopes for commits that we're working with are:
- planner
- profile
- auth
- onboarding

# Requested Changes
I noticed that you used placeholder text when adding text. You should also restrict adding courses to the table unless there are valid values for all fields.

![image](https://user-images.githubusercontent.com/16641570/127781653-a12e457b-4410-4878-989d-cadd109f6638.png)

Since the component you made displays the "Course History" header with the rest of the page, the heading text is now redundant. What do you think you can do to de-duplicate the header?

![image](https://user-images.githubusercontent.com/16641570/127781772-0b9bc0d7-ad0e-4ef2-8029-0ec6b8bca760.png)

P.S.: Next time, make sure to re-request the review so the reviewer(s) get pinged. :)

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  return years.reverse();
I would recommend looking into JavaScript functions like [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) and `reduce` to see how you can simplify operations like this.

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  updateSelectedState(courses: string[]): any;
This is how function types are supposed to look:
```suggestion
  update: (courses: CourseAttempt[]) => any;
  updateNum: (courses: string[]) => any;
  updateSelectedState: (courses: string[]) => any;
```
Additionally, you should not be using `any` types unless you're certain they're necessary. What is the most restrictive variable type that you can use with these functions?

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const deleteStuff = () => {
Use clearer language instead of `stuff` so others can understand what this function does when it's being referenced elsewhere in the code.

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const [year, setYear] = React.useState(2020);
Values like `2020` should be constants at the top level of the file and referenced where needed.

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const [courseName, setName] = React.useState('PLACEHOLDER');
Don't use a placeholder. Just use an empty string:
```suggestion
  const [courseName, setName] = React.useState('');
```

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const [season, setSeason] = React.useState('Spring');
Instead of explicitly using a hard-coded season, use the already existing `SemesterCode` type as the default value to avoid potential errors.

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const [grade, setGrade] = React.useState('A+');
Similar to the previous line, use an already existing data type for initial state: I believe it's a `Grade` type.

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const temp = data.slice();
Don't use "temp" variables. If it's only used once, inline it or group it with the places where it's used. Additionally, rename it so its purpose is clear.

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +  const addStuff = () => {
See the comment on line 359.

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +              ></TextField>
```suggestion
             />
```

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +                  name={'Season'}
```suggestion
                  name="Season"
```

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +                  name={'Grade'}
```suggestion
                  name="Grade"
```

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +      })()}
It's not entirely clear what's going on here. You're using an IIFE, but is that necessary here? Could you extract this into a variable that's computed before the final return call on this function?

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +      })()}
See the comments on lines 418 to 486.

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +//Calculates based on a rational function with a constant
Use doc comments, and could you be more clear what "based on a rational function with a constant" means?
```suggestion
/**
 * Colors the grade according to its GPA value.
 */
```

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +function colorMeBlue(grade) {
Does this function name best describe what's happening in this function?
```suggestion
function colorMeBlue(grade) {
```

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +}
```suggestion
}

```

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +                <TableRow style={{ height: (dense ? 33 : 53) * emptyRows }}>
Where do the constants 33 and 53 come from?

2021-08-01 19:22 UTC, WillieCubed commented on components/planner/history/StudentHistoryView/CourseAudit.tsx
> +export default function EnhancedTable() {
This component needs documentation and a brief tidbit on usage. What does it do?

2021-08-20 18:41 UTC, WillieCubed commented
#### 📝 Changed routes:


| [**/app/profile**](https://nebula-web-m6gctjv4s-acmutd.vercel.app/app/profile) |
|:-:|
|<a href="https://nebula-web-m6gctjv4s-acmutd.vercel.app/app/profile"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/GcjM0CTKSOPelIHESmhJe24fIrgOgmuDfa9pp6Ld92s7uQATbd8oeP2AsPWa3acbB1zn6Sx8KzFEXGEewEt-mA.png&w=600" alt="Screenshot of /app/profile" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/WWQlCabwyqW_N05Nj9m1HjukeFYh7z341lwzKuomU7UnYS7MjhagfXReFqU_lZqmcTKL0G54OlevG5C7E1nzIQ.png">(view full size)</a> |







Commit 6166c334937995730e436ca8da1ca350a939c8b6 (https://nebula-web-m6gctjv4s-acmutd.vercel.app).

2022-02-04 20:05 UTC, closed without merging