Feat: New Onboarding UI.
UTDNebula/planner pull request #57
Opened 2021-09-14 17:50 UTC by rajmeet2001

## Overview

Prior to this PR, the old onboarding was missing proper questions and UI flow. Now the new onboarding flow is being implemented using Tailwind CSS components. The questions are taken from the `Onboarding Flow Ideas` discussion. 

## What Changed

The `onboarding.tsx` file saw an overhaul in terms of adding the new HTML code for onboarding. Additionally, a folder with all the HTML code for the various `Onboarding-Pages` has been added.

## Other Notes

The backend implementation for the buttons and drop-down menus needs to be handled. 
This PR includes some bug fixes from the `feature/course-audit` branch that will be merged soon.

2021-09-14 18:24 UTC, NickBurnett commented on components/home/HomeUserInfo.tsx
> +  const { coursesTaken, coursesRemaining, hoursAttempted, gpa, estimatedGraduation } =
Lexicographical maybe?

2021-09-14 18:24 UTC, NickBurnett commented on pages/Onboarding_Pages/pg_1.tsx
> +const subjects = ['Computer Science', 'Biology', 'Gender Studies'];
Are there going to be more majors?

2021-09-14 18:24 UTC, NickBurnett commented on report.20210820.124342.4275.0.001.json
> +
What is this file?

2021-09-14 19:27 UTC, rajmeet2001 commented on pages/Onboarding_Pages/pg_1.tsx
> +const subjects = ['Computer Science', 'Biology', 'Gender Studies'];
Yup.

2021-09-14 19:28 UTC, rajmeet2001 commented on report.20210820.124342.4275.0.001.json
> +
No idea. Maybe some auto-generated log file

2021-09-14 19:29 UTC, rajmeet2001 commented on components/home/HomeUserInfo.tsx
> +  const { coursesTaken, coursesRemaining, hoursAttempted, gpa, estimatedGraduation } =
Possible.

2021-09-14 19:35 UTC, WillieCubed commented on report.20210820.124342.4275.0.001.json
> +
Figure out what generated the file and add it to the .gitignore if it's unavoidable. Delete it before merging.

2021-09-14 19:35 UTC, WillieCubed commented on pages/Onboarding_Pages/pg_1.tsx
> +const subjects = ['Computer Science', 'Biology', 'Gender Studies'];
Instead of hardcoding the majors, this should be data fetched from the app's data store, which in turn fetches it from a centralized configuration file or remote source.

2021-10-04 00:14 UTC, WillieCubed commented
#### 📝 Changed routes:


| [**…rding_Pages/disclaimer**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/disclaimer) | [**/Onboarding_Pages/pg_1**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/pg_1) |
|:-:|:-:|
|<a href="https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/disclaimer"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/DEeYoCQuARXh9UlGv-YswV9jdAEBArLiLBcZlQlpYfiX1RaQS2N0-TKIBwTxBsVvV40xvP9jJCdQOd6KX5envw.png&w=600" alt="Screenshot of /Onboarding_Pages/disclaimer" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ErPVLjVNokxOhf4BiYCT23iicxmURyqV_7JwfvixqssC7k9sjfghwV1zwSSii3fuSIsh-Zbtwx-c02EQzkWkgg.png">(view full size)</a> |<a href="https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/pg_1"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/r-F3sjiN3b-exs5sd3-4r4_dh2l6k7l90LSgh_hMPIHRNOf_WeeOav3MQba6pF46ZRHBqNH1_GwTfCONyxtZQw.png&w=600" alt="Screenshot of /Onboarding_Pages/pg_1" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/bpW1sAHy-EJn7sxtI7BMYiHI74xoqp9Djzn1kPIdnbbr_ctep6kYfv2aAWHi-sOMi4zAeUV4j1aDwQXepsi-Qg.png">(view full size)</a> |



| [**/Onboarding_Pages/pg_2**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/pg_2) | [**/Onboarding_Pages/pg_3**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/pg_3) |
|:-:|:-:|
|<a href="https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/pg_2"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/PcM55ItWhvPac-R1NQfaictVnflS6MFW-lMFg-SFVCu_5sBykme_Hs__sdw7b5Z-0gkTQiVqZPzqkd05TEAgHA.png&w=600" alt="Screenshot of /Onboarding_Pages/pg_2" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/3MFmrOjAkMms2rLbdb2v9JRq8XPXO721HeuSboaRM0bpOrmY87sgxxnYtaqvjybinkuri5vc5S7iJH2kQi0hHQ.png">(view full size)</a> |<a href="https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/pg_3"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/dif3Vj15kklS_ClW7fSTZh2kydV4J89p_4xtmyMXsyzca2i3uGRP0Nk0N8lDV1X4lG8-Tw5qwwsRCAVJ_dfZfw.png&w=600" alt="Screenshot of /Onboarding_Pages/pg_3" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xdyRVEjiulucrJBKKJBBYMnXonqP1UmEMjSaQdfbibfjTvGQR8301oyiZJq21K84kM7PpLt8p3UMAXa4ZK4q2A.png">(view full size)</a> |



| [**/Onboarding_Pages/pg_4**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/pg_4) | [**/Onboarding_Pages/privacy**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/privacy) |
|:-:|:-:|
|<a href="https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/pg_4"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/LGZQDhqCs0fmTVxbMPNbfXuXUWHScFa1mrZAfkzA2UWB1XLSuooBaOHFfPetI69h1ODyad4-uu0uv_SMc_fccA.png&w=600" alt="Screenshot of /Onboarding_Pages/pg_4" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/C0b_WLQiEefPk7kYF_aoIK6E50VuGhBawMXajPihEPDC0hRreW1yGgEIbrOi9K87whr-28TKA4RfGMPyeOp0HQ.png">(view full size)</a> |<a href="https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/privacy"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/RF6MN3zNqmUgtgizLoffPN4pqmRcjVdRM5Q0QKFX3_Blfds24aago9B_TDzYhM9-wGM5Pf1Dunhu1pBSTZhEVQ.png&w=600" alt="Screenshot of /Onboarding_Pages/privacy" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Ke7Dkr0BMEQViNLpIIAgjMQ_Y3MHLh-79nG5JGfZNYx-g6ocXpmT49YP2Dz0ET0cW-iUGLZU2wN3hN0P7Tu-lQ.png">(view full size)</a> |



And 4 other routes:
- [**/Onboarding_Pages/welcome**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/Onboarding_Pages/welcome)
- [**/app/onboarding**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/app/onboarding)
- [**/app/onboarding_old**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/app/onboarding_old)
- [**/app/profile**](https://nebula-web-qmjf61hg9-acmutd.vercel.app/app/profile)



Commit ad0b93a04ff521db5d6d918bd934ce8dade09563 (https://nebula-web-qmjf61hg9-acmutd.vercel.app).

2021-10-04 01:08 UTC, rajmeet2001 commented
The navigation buttons seem to have disappeared from the main pages of the onboarding. @ZzRanger

2021-10-04 02:32 UTC, ZzRanger commented
> The navigation buttons seem to have disappeared from the main pages of the onboarding. @ZzRanger

I didn't add navigation buttons to the main onboarding pages in my initial commit. I'll make another commit adding those buttons to all the pages.

2021-11-09 05:56 UTC, ZzRanger commented
All the work I planned on doing on onboarding for now is complete. I will need to redesign the UI once new mockups are made on Figma, but that won't take too much time. Unless anyone has any issues, this branch is ready to be merged.

2021-11-10 16:16 UTC, rajmeet2001 commented on pages/Onboarding_Pages/pg_3.tsx
> -const subjects = ['Computer Science', 'Biology', 'Gender Studies'];
Just as heads up: All of these variables will be probably be dissolved once the Nebula API comes online.

2021-11-10 22:57 UTC, WillieCubed requested changes
Can you extract all hard-coded values into a separate file so it'll be easier to identify what data should come from the API when we refactor it?

2022-02-04 20:05 UTC, merged