refactor(NP-82): Remove legacy credits components
UTDNebula/planner pull request #609
Opened 2023-07-20 01:22 UTC by akevinge

2023-07-20 01:24 UTC, akevinge commented on src/components/planner/Sidebar/SearchBar.tsx
This was moved from `src/components/credits/SearchBar.tsx`.

2023-07-21 23:18 UTC, jasonappah requested changes
LGTM, do we also want to get rid of the credit model?

2023-07-29 01:04 UTC, akevinge commented
> LGTM, do we also want to get rid of the credit model?

Done.

2023-07-30 02:55 UTC, jasonappah approved these changes

2023-07-30 04:03 UTC, merged